#!/usr/bin/env python3
"""Generate native Rust and Go tables from the shared SOTN codec spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = Path(__file__).with_name("spec.json")
RUST_PATH = ROOT / "tools" / "sotn_str" / "src" / "generated_codec.rs"
GO_PATH = ROOT / "tools" / "sotn-assets" / "sotn" / "generated_codec.go"


def load_spec() -> dict:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    if spec.get("version") != 1:
        raise ValueError("unsupported codec spec version")
    for name, platform in spec["platforms"].items():
        rows = platform["rows"]
        if len(rows) != 16:
            raise ValueError(f"{name} has {len(rows)} rows, expected 16")
        for index, row in enumerate(rows):
            if len(row) != 16:
                raise ValueError(
                    f"{name} row {index:X} has {len(row)} glyphs, expected 16"
                )
    return spec


def glyphs(spec: dict, platform: str) -> list[str]:
    return list("".join(spec["platforms"][platform]["rows"]))


def rust_char(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def go_rune(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def chunks(values: list[str], size: int = 8) -> list[list[str]]:
    return [values[index : index + size] for index in range(0, len(values), size)]


def generate_rust(spec: dict) -> str:
    lines = [
        "// Code generated by tools/sotn_codec/generate.py; DO NOT EDIT.",
        "",
        f"pub const ESCAPE_BYTE: u8 = 0x{spec['escape_byte']:02X};",
        f"pub const LITERAL_ESCAPE_GLYPH: char = {rust_char(spec['literal_escape_glyph'])};",
        f"pub const DAKUTEN_MARK: u8 = 0x{spec['voice_marks']['dakuten']:02X};",
        f"pub const HANDAKUTEN_MARK: u8 = 0x{spec['voice_marks']['handakuten']:02X};",
        "",
    ]
    for platform in ("psx", "psp"):
        name = f"{platform.upper()}_FONT_TABLE"
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub const {name}: [char; 256] = [")
        values = [rust_char(value) for value in glyphs(spec, platform)]
        for row in chunks(values, 8):
            lines.append(f"    {', '.join(row)},")
        lines.extend(["];"])
        lines.append("")
    for kind in ("dakuten", "handakuten"):
        name = f"{kind.upper()}_COMPOSITIONS"
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub const {name}: &[(char, char)] = &[")
        for base, composed in spec["compositions"][kind]:
            lines.append(
                f"    ({rust_char(base)}, {rust_char(composed)}),"
            )
        lines.extend(["];", ""])
    return "\n".join(lines)


def generate_go(spec: dict) -> str:
    lines = [
        "// Code generated by tools/sotn_codec/generate.py; DO NOT EDIT.",
        "",
        "package sotn",
        "",
        "const (",
        f"\tstringEscapeByte   byte = 0x{spec['escape_byte']:02X}",
        f"\tliteralEscapeGlyph rune = {go_rune(spec['literal_escape_glyph'])}",
        f"\tdakutenMark        byte = 0x{spec['voice_marks']['dakuten']:02X}",
        f"\thandakutenMark     byte = 0x{spec['voice_marks']['handakuten']:02X}",
        ")",
        "",
    ]
    for platform in ("psx", "psp"):
        lines.append(f"var {platform}FontTable = []rune{{")
        values = [go_rune(value) for value in glyphs(spec, platform)]
        for row in chunks(values, 8):
            lines.append(f"\t{', '.join(row)},")
        lines.extend(["}", ""])
    for kind in ("dakuten", "handakuten"):
        lines.append(f"var {kind} = map[rune]rune{{")
        for base, composed in spec["compositions"][kind]:
            lines.append(f"\t{go_rune(base)}: {go_rune(composed)},")
        lines.extend(["}", ""])
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    content = content.rstrip() + "\n"
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            print(f"generated codec file is stale: {path.relative_to(ROOT)}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files differ"
    )
    args = parser.parse_args()
    try:
        spec = load_spec()
        ok = write_or_check(RUST_PATH, generate_rust(spec), args.check)
        ok = write_or_check(GO_PATH, generate_go(spec), args.check) and ok
        return 0 if ok else 1
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"codec generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
